export const ECOSYSTEM_HEADER = "X-Ecosystem";
export const PUBLIC_WHITE_LABEL_BOARD_ROUTE_HEADER =
  "X-WHITE-LABEL-BOARD-ROUTE";
export const PUBLIC_WHITE_LABEL_BOARD_DOMAIN_HEADER =
  "X-WHITE-LABEL-BOARD-DOMAIN";
