export const USER_ROLES = {
  ANON: "ANON",
  ADMIN: "ADMIN",
  DEV: "DEV",
  ORG: "ORG",
} as const;

export const USER_FLOWS = {
  PICK_ROLE: "PICK-ROLE",
  ADD_GITHUB_REPO: "ADD-GITHUB-REPO",
  ONBOARD_REPO: "ONBOARD-REPO",
  ONBOARD_PROFILE: "ONBOARD-PROFILE",
  SIGNUP_COMPLETE: "SIGNUP-COMPLETE",
  ADMIN_SYNONYMS: "SYNONYMS",
  ORG_ONBOARD: "ORG-ONBOARD",
  ADMIN_COMPLETE: "ADMIN-COMPLETE",
} as const;
