import { SearchNav } from "../interfaces";

export const NAV_FILTER_LABEL_MAPPINGS: Record<
  SearchNav,
  Record<string, string> | null
> = {
  projects: {
    categories: "Categories",
    chains: "Chains",
    organizations: "Organizations",
    investors: "Investors",
    names: "Projects",
    tags: "Tags",
  },
  organizations: {
    locations: "Locations",
    investors: "Investors",
    fundingRounds: "Funding Rounds",
    fundingStages: "Current Funding Stage",
    chains: "Chains",
    names: "Organizations",
    tags: "Tags",
    projects: "Projects",
  },
  jobs: {
    tags: "Tags",
    locations: "Locations",
    commitments: "Commitments",
    locationTypes: "Location Types",
    timezones: "Timezones",
    collaborationHours: "Likely Team Collaboration Hours (UTC)",
    classifications: "Classifications",
    seniority: "Seniority",
    organizations: "Organizations",
    investors: "Investors",
    fundingRounds: "Funding Rounds",
    fundingStages: "Current Funding Stage",
  },
  vcs: null,
};

export const NAV_PILLAR_ORDERING: Record<SearchNav, string[]> = {
  organizations: [
    "investors",
    "locations",
    "projects",
    "chains",
    "fundingRounds",
    "fundingStages",
    "names",
    "tags",
  ],
  projects: [
    "categories",
    "chains",
    "organizations",
    "investors",
    "names",
    "tags",
  ],
  jobs: [
    "classifications",
    "organizations",
    "tags",
    "locationTypes",
    "timezones",
    "collaborationHours",
    "locations",
    "commitments",
    "seniority",
    "investors",
    "fundingRounds",
    "fundingStages",
  ],
  vcs: ["names"],
};

export const NAV_FILTER_CONFIGS: Record<SearchNav, string[] | null> = {
  projects: [
    "ecosystems",
    "tvl",
    "monthlyVolume",
    "monthlyFees",
    "monthlyRevenue",
    "audits",
    "hacks",
    "token",
    "order",
    "orderBy",
  ],
  organizations: [
    "headCount",
    "ecosystems",
    "hasJobs",
    "hasProjects",
    "fundingStages",
    "currentMaintainers",
    "activeLeads",
    "newActiveLeads",
    "steppedDownLeads",
    "movedLeads",
    "earlyLeadDepartures",
    "recentlyFunded",
    "order",
    "orderBy",
  ],
  jobs: [
    "tags",
    "locations",
    "commitments",
    "locationTypes",
    "timezones",
    "collaborationHours",
    "classifications",
    "seniority",
    "organizations",
    "investors",
    "fundingRounds",
    "fundingStages",
  ],
  vcs: null,
};

export const NAV_PILLAR_TITLES: Record<SearchNav, string> = {
  organizations: "Organization",
  projects: "Project",
  jobs: "Job",
  vcs: "VC",
};

export const NAV_PILLAR_SLUG_PREFIX_MAPPINGS: Record<
  SearchNav,
  Record<string, string>
> = {
  projects: {
    categories: "c",
    chains: "ch",
    organizations: "o",
    investors: "i",
    names: "p",
    tags: "t",
  },
  organizations: {
    locations: "l",
    investors: "i",
    fundingRounds: "fr",
    fundingStages: "fs",
    chains: "ch",
    names: "o",
    tags: "t",
    projects: "p",
  },
  vcs: { names: "v" },
  jobs: {
    classifications: "cl",
    locations: "l",
    tags: "t",
    commitments: "co",
    locationTypes: "lt",
    timezones: "tz",
    collaborationHours: "ct",
    seniority: "s",
    organizations: "o",
    investors: "i",
    fundingRounds: "fr",
    fundingStages: "fs",
    booleans: "b",
  },
};
