import { TEAM_SIGNAL_SINGLE_SELECT_OPTIONS } from "./team-signal-filter-options";

export enum FilterKind {
  SINGLE_SELECT = "SINGLE_SELECT",
  RANGE = "RANGE",
  MULTI_SELECT = "MULTI_SELECT",
  MULTI_SELECT_WITH_SEARCH = "MULTI_SELECT_WITH_SEARCH",
}

export const SINGLE_SELECT_OPTIONS = {
  publicationDate: [
    { label: "Today", value: "today" },
    { label: "This Week", value: "this-week" },
    { label: "This Month", value: "this-month" },
    { label: "Past 2 Weeks", value: "past-2-weeks" },
    { label: "Past 3 Months", value: "past-3-months" },
    { label: "Past 6 Months", value: "past-6-months" },
  ],
  hacks: [
    { label: "Has been hacked", value: true },
    { label: "Has not been hacked", value: false },
  ],
  audits: [
    { label: "Has Audits", value: true },
    { label: "Has No Audits", value: false },
  ],
  token: [
    { label: "Has Token", value: true },
    { label: "Has No Token", value: false },
  ],
  onboardIntoWeb3: [
    { label: "Web3 Beginner Friendly", value: true },
    { label: "Not Web3 Beginner Friendly", value: false },
  ],
  expertJobs: [
    { label: "Expert Jobs", value: true },
    { label: "Not Expert Jobs", value: false },
  ],
  ...TEAM_SIGNAL_SINGLE_SELECT_OPTIONS,
  order: [
    { label: "A-Z", value: "asc" },
    { label: "Z-A", value: "desc" },
  ],
  orderBy: [
    { label: "Funding Date", value: "fundingDate" },
    { label: "Head Count", value: "headcountEstimate" },
    { label: "Monthly Fees", value: "monthlyFees" },
    { label: "Monthly Revenue", value: "monthlyRevenue" },
    { label: "Monthly Volume", value: "monthlyVolume" },
    { label: "Number of Audits", value: "audits" },
    { label: "Number of Chains", value: "chains" },
    { label: "Number of Hacks", value: "hacks" },
    { label: "Publication Date", value: "publicationDate" },
    { label: "Salary", value: "salary" },
    { label: "TVL", value: "tvl" },
    { label: "Team Size", value: "teamSize" },
  ],
};

export const FILTER_CONFIG_PRESETS = {
  publicationDate: {
    position: 0,
    label: "Publication Date",
    show: true,
    googleAnalyticsEventName: "filter_joblist_publication_date",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.publicationDate,
  },
  classifications: {
    position: 1,
    label: "Category",
    show: true,
    googleAnalyticsEventName: "filter_joblist_classifications",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  commitments: {
    position: 2,
    label: "Commitment",
    show: true,
    googleAnalyticsEventName: "filter_joblist_commitments",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  ecosystems: {
    position: 3,
    label: "Ecosystems",
    show: false,
    googleAnalyticsEventName: "filter_joblist_ecosystems",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  salary: {
    position: 4,
    label: "Salary",
    show: true,
    googleAnalyticsEventName: "filter_joblist_salary",
    kind: FilterKind.RANGE,
    prefix: "$",
  },
  seniority: {
    position: 5,
    label: "Seniority",
    show: true,
    googleAnalyticsEventName: "filter_joblist_seniority",
    kind: FilterKind.MULTI_SELECT,
  },
  locations: {
    position: 6,
    label: "Location",
    show: false,
    googleAnalyticsEventName: "filter_joblist_location",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  workModes: {
    position: 25,
    label: "Work Mode",
    show: true,
    googleAnalyticsEventName: "filter_joblist_work_modes",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  availability: {
    position: 90,
    label: "Candidate Availability",
    show: false,
    googleAnalyticsEventName: "filter_joblist_availability",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  countries: {
    position: 26,
    label: "Country",
    show: true,
    googleAnalyticsEventName: "filter_joblist_countries",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  regions: {
    position: 27,
    label: "Region",
    show: true,
    googleAnalyticsEventName: "filter_joblist_regions",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  cities: {
    position: 28,
    label: "City",
    show: true,
    googleAnalyticsEventName: "filter_joblist_cities",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  continents: {
    position: 29,
    label: "Continent",
    show: true,
    googleAnalyticsEventName: "filter_joblist_continents",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  timezones: {
    position: 30,
    label: "Timezone",
    show: true,
    googleAnalyticsEventName: "filter_joblist_timezones",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  collaborationHours: {
    position: 31,
    label: "Likely Team Collaboration Hours (UTC)",
    show: true,
    googleAnalyticsEventName: "filter_joblist_collaboration_hours",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  fundingStages: {
    position: 32,
    label: "Current Funding Stage",
    show: true,
    googleAnalyticsEventName: "filter_joblist_funding_stages",
    kind: FilterKind.MULTI_SELECT,
  },
  currentMaintainers: {
    position: 33,
    label: "Current Maintainers",
    show: true,
    googleAnalyticsEventName: "filter_joblist_current_maintainers",
    kind: FilterKind.RANGE,
    prefix: null,
  },
  activeLeads: {
    position: 34,
    label: "Active Leads",
    show: true,
    googleAnalyticsEventName: "filter_joblist_active_leads",
    kind: FilterKind.RANGE,
    prefix: null,
  },
  newActiveLeads: {
    position: 35,
    label: "New Active Leads",
    show: true,
    googleAnalyticsEventName: "filter_joblist_new_active_leads",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.newActiveLeads,
  },
  steppedDownLeads: {
    position: 36,
    label: "Lead Step-Downs",
    show: true,
    googleAnalyticsEventName: "filter_joblist_stepped_down_leads",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.steppedDownLeads,
  },
  movedLeads: {
    position: 37,
    label: "Lead Movements",
    show: true,
    googleAnalyticsEventName: "filter_joblist_moved_leads",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.movedLeads,
  },
  earlyLeadDepartures: {
    position: 38,
    label: "Early Lead Departures",
    show: true,
    googleAnalyticsEventName: "filter_joblist_early_lead_departures",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.earlyLeadDepartures,
  },
  growingTeam: {
    position: 90,
    label: "New Active Leads (legacy)",
    show: false,
    googleAnalyticsEventName: "filter_joblist_growing_team",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.growingTeam,
  },
  shrinkingTeam: {
    position: 91,
    label: "Lead Step-Downs (legacy)",
    show: false,
    googleAnalyticsEventName: "filter_joblist_shrinking_team",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.shrinkingTeam,
  },
  earlyTeamShrinkage: {
    position: 92,
    label: "Early Lead Departures (legacy)",
    show: false,
    googleAnalyticsEventName: "filter_joblist_early_team_shrinkage",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.earlyTeamShrinkage,
  },
  recentlyFunded: {
    position: 39,
    label: "Recently Funded",
    show: true,
    googleAnalyticsEventName: "filter_joblist_recently_funded",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.recentlyFunded,
  },
  headcountEstimate: {
    position: 7,
    label: "Head Count",
    show: true,
    googleAnalyticsEventName: "filter_joblist_head_count",
    kind: FilterKind.RANGE,
    prefix: null,
  },
  tags: {
    position: 8,
    label: "Skills",
    show: true,
    googleAnalyticsEventName: "filter_joblist_tags",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  fundingRounds: {
    position: 9,
    label: "Funding Rounds",
    show: true,
    googleAnalyticsEventName: "filter_joblist_funding_rounds",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  investors: {
    position: 10,
    label: "Investors",
    show: true,
    googleAnalyticsEventName: "filter_joblist_investors",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  audits: {
    position: 11,
    label: "Audits",
    show: true,
    googleAnalyticsEventName: "filter_joblist_audits",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.audits,
  },
  hacks: {
    position: 12,
    label: "Hacks",
    show: true,
    googleAnalyticsEventName: "filter_joblist_hacks",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.hacks,
  },
  chains: {
    position: 13,
    label: "Chains",
    show: true,
    googleAnalyticsEventName: "filter_joblist_chains",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  organizations: {
    position: 14,
    label: "Organizations",
    show: true,
    googleAnalyticsEventName: "filter_joblist_organizations",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  projects: {
    position: 15,
    label: "Projects",
    show: true,
    googleAnalyticsEventName: "filter_joblist_projects",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  tvl: {
    position: 16,
    label: "TVL",
    show: true,
    googleAnalyticsEventName: "filter_joblist_tvl",
    kind: FilterKind.RANGE,
    prefix: "$",
  },
  monthlyVolume: {
    position: 17,
    label: "Volume/mo",
    show: false,
    googleAnalyticsEventName: "filter_joblist_monthly_volume",
    kind: FilterKind.RANGE,
    prefix: "$",
  },
  monthlyFees: {
    position: 18,
    label: "Fees/mo",
    show: false,
    googleAnalyticsEventName: "filter_joblist_monthly_fees",
    kind: FilterKind.RANGE,
    prefix: "$",
  },
  monthlyRevenue: {
    position: 19,
    label: "Revenue/mo",
    show: false,
    googleAnalyticsEventName: "filter_joblist_monthly_revenue",
    kind: FilterKind.RANGE,
    prefix: "$",
  },
  token: {
    position: 20,
    label: "Has Token",
    show: true,
    googleAnalyticsEventName: "filter_joblist_has_token",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.token,
  },
  onboardIntoWeb3: {
    position: 21,
    label: "Web3 Beginner Friendly",
    show: true,
    googleAnalyticsEventName: "filter_joblist_onboard_into_web3",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.onboardIntoWeb3,
  },
  expertJobs: {
    position: 22,
    label: "Expert Jobs",
    show: true,
    googleAnalyticsEventName: "filter_joblist_expert_jobs",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.expertJobs,
  },
  orderBy: {
    position: 23,
    label: "Order By",
    show: true,
    googleAnalyticsEventName: "filter_joblist_order_by",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.orderBy,
  },
  order: {
    position: 24,
    label: "Order",
    show: true,
    googleAnalyticsEventName: "filter_joblist_order",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.order,
  },
};

export const FILTER_PARAM_KEY_PRESETS = {
  publicationDate: "publicationDate",
  salary: {
    lowest: "minSalaryRange",
    highest: "maxSalaryRange",
  },
  seniority: "seniority",
  locations: "locations",
  workModes: "workModes",
  availability: "availability",
  cities: "cities",
  regions: "regions",
  countries: "countries",
  continents: "continents",
  timezones: "timezones",
  collaborationHours: "collaborationHours",
  fundingStages: "fundingStages",
  currentMaintainers: {
    lowest: "minCurrentMaintainers",
    highest: "maxCurrentMaintainers",
  },
  activeLeads: {
    lowest: "minActiveLeads",
    highest: "maxActiveLeads",
  },
  newActiveLeads: "newActiveLeads",
  steppedDownLeads: "steppedDownLeads",
  movedLeads: "movedLeads",
  earlyLeadDepartures: "earlyLeadDepartures",
  growingTeam: "growingTeam",
  shrinkingTeam: "shrinkingTeam",
  earlyTeamShrinkage: "earlyTeamShrinkage",
  recentlyFunded: "recentlyFunded",
  headcountEstimate: {
    lowest: "minHeadCount",
    highest: "maxHeadCount",
  },
  tags: "tags",
  fundingRounds: "fundingRounds",
  investors: "investors",
  organizations: "organizations",
  chains: "chains",
  ecosystems: "ecosystems",
  projects: "projects",
  classifications: "classifications",
  commitments: "commitments",
  tvl: {
    lowest: "minTvl",
    highest: "maxTvl",
  },
  monthlyVolume: {
    lowest: "minMonthlyVolume",
    highest: "maxMonthlyVolume",
  },
  monthlyFees: {
    lowest: "minMonthlyFees",
    highest: "maxMonthlyFees",
  },
  monthlyRevenue: {
    lowest: "minMonthlyRevenue",
    highest: "maxMonthlyRevenue",
  },
  audits: "audits",
  hacks: "hacks",
  token: "token",
  onboardIntoWeb3: "onboardIntoWeb3",
  expertJobs: "expertJobs",
  order: "order",
  orderBy: "orderBy",
};
