export enum FilterKind {
  SINGLE_SELECT = "SINGLE_SELECT",
  RANGE = "RANGE",
  MULTI_SELECT = "MULTI_SELECT",
  MULTI_SELECT_WITH_SEARCH = "MULTI_SELECT_WITH_SEARCH",
}

export const SINGLE_SELECT_OPTIONS = {
  hasProjects: [
    { label: "Has projects", value: true },
    { label: "Has no projects", value: false },
  ],
  hasJobs: [
    { label: "Has jobs", value: true },
    { label: "Has no jobs", value: false },
  ],
  growingTeam: [
    { label: "Growing maintainer team", value: true },
    { label: "Not growing", value: false },
  ],
  shrinkingTeam: [
    { label: "Maintainers moved", value: true },
    { label: "No detected maintainer moves", value: false },
  ],
  earlyTeamShrinkage: [
    { label: "Early maintainers moved", value: true },
    { label: "No detected early-team moves", value: false },
  ],
  recentlyFunded: [
    { label: "Funded in the last 6 months", value: true },
    { label: "No funding event in the last 6 months", value: false },
  ],
  order: [
    { label: "Ascending", value: "asc" },
    { label: "Descending", value: "desc" },
  ],
  orderBy: [
    { label: "Head Count", value: "headcountEstimate" },
    { label: "Most Recent Jobpost", value: "recentJobDate" },
    { label: "Most Recent Funding Date", value: "recentFundingDate" },
    { label: "Rating", value: "rating" },
    { label: "Name", value: "name" },
  ],
};

export const FILTER_CONFIG_PRESETS = {
  locations: {
    position: 1,
    label: "Locations",
    show: true,
    googleAnalyticsEventName: "filter_orglist_locations",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  headcountEstimate: {
    position: 2,
    label: "Head Count",
    show: true,
    googleAnalyticsEventName: "filter_orglist_head_count",
    kind: FilterKind.RANGE,
    prefix: null,
  },
  fundingRounds: {
    position: 3,
    label: "Funding Rounds",
    show: true,
    googleAnalyticsEventName: "filter_orglist_funding_rounds",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  investors: {
    position: 4,
    label: "Investors",
    show: true,
    googleAnalyticsEventName: "filter_orglist_investors",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  ecosystems: {
    position: 5,
    label: "Ecosystems",
    show: true,
    googleAnalyticsEventName: "filter_joblist_ecosystems",
    kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
  },
  hasJobs: {
    position: 6,
    label: "Has Jobs",
    show: true,
    googleAnalyticsEventName: "filter_orglist_has_jobs",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.hasJobs,
  },
  hasProjects: {
    position: 7,
    label: "Has Projects",
    show: true,
    googleAnalyticsEventName: "filter_orglist_has_projects",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.hasProjects,
  },
  order: {
    position: 8,
    label: "Order",
    show: true,
    googleAnalyticsEventName: "filter_orglist_order",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.order,
  },
  orderBy: {
    position: 9,
    label: "Order By",
    show: true,
    googleAnalyticsEventName: "filter_orglist_order_by",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.orderBy,
  },
  // Appended (position 10) so existing filter positions stay stable.
  categories: {
    position: 10,
    label: "Categories",
    show: true,
    googleAnalyticsEventName: "filter_orglist_categories",
    kind: FilterKind.MULTI_SELECT,
  },
  fundingStages: {
    position: 11,
    label: "Current Funding Stage",
    show: true,
    googleAnalyticsEventName: "filter_orglist_funding_stages",
    kind: FilterKind.MULTI_SELECT,
  },
  currentMaintainers: {
    position: 12,
    label: "Current Maintainers",
    show: true,
    googleAnalyticsEventName: "filter_orglist_current_maintainers",
    kind: FilterKind.RANGE,
    prefix: null,
  },
  growingTeam: {
    position: 13,
    label: "Growing Maintainer Team",
    show: true,
    googleAnalyticsEventName: "filter_orglist_growing_team",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.growingTeam,
  },
  shrinkingTeam: {
    position: 14,
    label: "Maintainer Moves",
    show: true,
    googleAnalyticsEventName: "filter_orglist_shrinking_team",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.shrinkingTeam,
  },
  earlyTeamShrinkage: {
    position: 15,
    label: "Early-Team Moves",
    show: true,
    googleAnalyticsEventName: "filter_orglist_early_team_shrinkage",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.earlyTeamShrinkage,
  },
  recentlyFunded: {
    position: 16,
    label: "Recently Funded",
    show: true,
    googleAnalyticsEventName: "filter_orglist_recently_funded",
    kind: FilterKind.SINGLE_SELECT,
    options: SINGLE_SELECT_OPTIONS.recentlyFunded,
  },
};

export const FILTER_PARAM_KEY_PRESETS = {
  locations: "locations",
  headcountEstimate: {
    lowest: "minHeadCount",
    highest: "maxHeadCount",
  },
  fundingRounds: "fundingRounds",
  fundingStages: "fundingStages",
  currentMaintainers: {
    lowest: "minCurrentMaintainers",
    highest: "maxCurrentMaintainers",
  },
  growingTeam: "growingTeam",
  shrinkingTeam: "shrinkingTeam",
  earlyTeamShrinkage: "earlyTeamShrinkage",
  recentlyFunded: "recentlyFunded",
  investors: "investors",
  ecosystems: "ecosystems",
  hasJobs: "hasJobs",
  hasProjects: "hasProjects",
  order: "order",
  orderBy: "orderBy",
  categories: "categories",
};
