export enum FilterKind {
  SINGLE_SELECT = "SINGLE_SELECT",
  RANGE = "RANGE",
  MULTI_SELECT = "MULTI_SELECT",
  MULTI_SELECT_WITH_SEARCH = "MULTI_SELECT_WITH_SEARCH",
  ORDER = "ORDER",
  ORDER_BY = "ORDER_BY",
}

export const SINGLE_SELECT_OPTIONS = {
  projects: {
    // hacks: [
    //   { label: "Has been hacked", value: true },
    //   { label: "Has not been hacked", value: false },
    // ],
    // audits: [
    //   { label: "Has Audits", value: true },
    //   { label: "Has No Audits", value: false },
    // ],
    // mainNet: [
    //   { label: "Deployed on Mainnet", value: true },
    //   { label: "Not Deployed on Mainnet", value: false },
    // ],
    // token: [
    //   { label: "Has Token", value: true },
    //   { label: "Has No Token", value: false },
    // ],
    order: [
      { label: "Ascending", value: "asc" },
      { label: "Descending", value: "desc" },
    ],
    orderBy: [
      { label: "Monthly Fees", value: "monthlyFees" },
      { label: "Monthly Revenue", value: "monthlyRevenue" },
      { label: "Monthly Volume", value: "monthlyVolume" },
      { label: "Number of Audits", value: "audits" },
      { label: "Number of Chains", value: "chains" },
      { label: "Number of Hacks", value: "hacks" },
      { label: "Most Recent Funding Date", value: "recentFundingDate" },
      { label: "TVL", value: "tvl" },
    ],
  },
  organizations: {
    // hasProjects: [
    //   { label: "Has projects", value: true },
    //   { label: "Has no projects", value: false },
    // ],
    // hasJobs: [
    //   { label: "Has jobs", value: true },
    //   { label: "Has no jobs", value: false },
    // ],
    order: [
      { label: "Ascending", value: "asc" },
      { label: "Descending", value: "desc" },
    ],
    orderBy: [
      { label: "Head Count", value: "headcountEstimate" },
      { label: "Most Recent Funding Date", value: "recentFundingDate" },
      { label: "Rating", value: "rating" },
      { label: "Name", value: "name" },
    ],
  },
  grants: {
    order: [
      { label: "Ascending", value: "asc" },
      { label: "Descending", value: "desc" },
    ],
    orderBy: [
      { label: "Match Amount", value: "matchAmount" },
      { label: "Payout Time", value: "payoutTime" },
      { label: "Donated Amount", value: "donatedAmount" },
    ],
  },
  impact: {
    order: [
      { label: "Ascending", value: "asc" },
      { label: "Descending", value: "desc" },
    ],
    orderBy: [
      { label: "Match Amount", value: "matchAmount" },
      { label: "Payout Time", value: "payoutTime" },
      { label: "Donated Amount", value: "donatedAmount" },
    ],
  },
};

export const FILTER_CONFIG_PRESETS = {
  projects: {
    categories: {
      position: 1,
      label: "Categories",
      show: true,
      googleAnalyticsEventName: "filter_search_categories",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    chains: {
      position: 2,
      label: "Chains",
      show: true,
      googleAnalyticsEventName: "filter_search_chains",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    investors: {
      position: 3,
      label: "Investors",
      show: true,
      googleAnalyticsEventName: "filter_search_investors",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    names: {
      position: 4,
      label: "Names",
      show: false,
      googleAnalyticsEventName: "filter_search_names",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    tags: {
      position: 5,
      label: "Tags",
      show: true,
      googleAnalyticsEventName: "filter_search_tags",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    order: {
      position: 10,
      label: "Order",
      show: true,
      googleAnalyticsEventName: "filter_search_order",
      kind: FilterKind.ORDER,
      options: SINGLE_SELECT_OPTIONS.projects.order,
    },
    orderBy: {
      position: 11,
      label: "Order By",
      show: true,
      googleAnalyticsEventName: "filter_search_order_by",
      kind: FilterKind.ORDER_BY,
      options: SINGLE_SELECT_OPTIONS.projects.orderBy,
    },
  },
  organizations: {
    investors: {
      position: 1,
      label: "Investors",
      show: true,
      googleAnalyticsEventName: "filter_search_investors",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    locations: {
      position: 2,
      label: "Locations",
      show: true,
      googleAnalyticsEventName: "filter_joblist_locations",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    chains: {
      position: 3,
      label: "Chains",
      show: true,
      googleAnalyticsEventName: "filter_search_chains",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    fundingRounds: {
      position: 4,
      label: "Funding Rounds",
      show: true,
      googleAnalyticsEventName: "filter_search_funding_rounds",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    names: {
      position: 5,
      label: "Names",
      show: true,
      googleAnalyticsEventName: "filter_search_names",
      kind: FilterKind.SINGLE_SELECT,
      prefix: null,
    },
    tags: {
      position: 6,
      label: "Tags",
      show: true,
      googleAnalyticsEventName: "filter_search_tags",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    order: {
      position: 7,
      label: "Order",
      show: true,
      googleAnalyticsEventName: "filter_search_order",
      kind: FilterKind.ORDER,
      options: SINGLE_SELECT_OPTIONS.organizations.order,
    },
    orderBy: {
      position: 8,
      label: "Order By",
      show: true,
      googleAnalyticsEventName: "filter_search_order_by",
      kind: FilterKind.ORDER_BY,
      options: SINGLE_SELECT_OPTIONS.organizations.orderBy,
    },
  },
  grants: {
    categories: {
      position: 1,
      label: "Categories",
      show: true,
      googleAnalyticsEventName: "filter_search_categories",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    chains: {
      position: 2,
      label: "Chains",
      show: true,
      googleAnalyticsEventName: "filter_search_chains",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    ecosystems: {
      position: 3,
      label: "Ecosystems",
      show: true,
      googleAnalyticsEventName: "filter_search_ecosystems",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    organizations: {
      position: 4,
      label: "Organizations",
      show: true,
      googleAnalyticsEventName: "filter_search_organizations",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    names: {
      position: 5,
      label: "Names",
      show: true,
      googleAnalyticsEventName: "filter_search_names",
      kind: FilterKind.SINGLE_SELECT,
      prefix: null,
    },
    order: {
      position: 6,
      label: "Order",
      show: true,
      googleAnalyticsEventName: "filter_search_order",
      kind: FilterKind.ORDER,
      options: SINGLE_SELECT_OPTIONS.grants.order,
    },
    orderBy: {
      position: 11,
      label: "Order By",
      show: true,
      googleAnalyticsEventName: "filter_search_order_by",
      kind: FilterKind.ORDER_BY,
      options: SINGLE_SELECT_OPTIONS.grants.orderBy,
    },
  },
  impact: {
    categories: {
      position: 1,
      label: "Categories",
      show: true,
      googleAnalyticsEventName: "filter_search_categories",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    chains: {
      position: 2,
      label: "Chains",
      show: true,
      googleAnalyticsEventName: "filter_search_chains",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    ecosystems: {
      position: 3,
      label: "Ecosystems",
      show: true,
      googleAnalyticsEventName: "filter_search_ecosystems",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    organizations: {
      position: 4,
      label: "Organizations",
      show: true,
      googleAnalyticsEventName: "filter_search_organizations",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
      prefix: null,
    },
    names: {
      position: 5,
      label: "Names",
      show: true,
      googleAnalyticsEventName: "filter_search_names",
      kind: FilterKind.SINGLE_SELECT,
      prefix: null,
    },
    order: {
      position: 6,
      label: "Order",
      show: true,
      googleAnalyticsEventName: "filter_search_order",
      kind: FilterKind.ORDER,
      options: SINGLE_SELECT_OPTIONS.impact.order,
    },
    orderBy: {
      position: 11,
      label: "Order By",
      show: true,
      googleAnalyticsEventName: "filter_search_order_by",
      kind: FilterKind.ORDER_BY,
      options: SINGLE_SELECT_OPTIONS.impact.orderBy,
    },
  },
};
