export enum FilterKind {
  SINGLE_SELECT = "SINGLE_SELECT",
  RANGE = "RANGE",
  MULTI_SELECT = "MULTI_SELECT",
  MULTI_SELECT_WITH_SEARCH = "MULTI_SELECT_WITH_SEARCH",
  ORDER = "ORDER",
  ORDER_BY = "ORDER_BY",
}

export const SINGLE_SELECT_OPTIONS = {
  projects: {
    hacks: [
      { label: "Has been hacked", value: true },
      { label: "Has not been hacked", value: false },
    ],
    audits: [
      { label: "Has Audits", value: true },
      { label: "Has No Audits", value: false },
    ],
    mainNet: [
      { label: "Deployed on Mainnet", value: true },
      { label: "Not Deployed on Mainnet", value: false },
    ],
    token: [
      { label: "Has Token", value: true },
      { label: "Has No Token", value: false },
    ],
    order: [
      { label: "Ascending", value: "asc" },
      { label: "Descending", value: "desc" },
    ],
    orderBy: [
      { label: "Monthly Fees", value: "monthlyFees" },
      { label: "Monthly Revenue", value: "monthlyRevenue" },
      { label: "Monthly Volume", value: "monthlyVolume" },
      { label: "Number of Audits", value: "audits" },
      { label: "Number of Chains", value: "chains" },
      { label: "Number of Hacks", value: "hacks" },
      { label: "Most Recent Funding Date", value: "recentFundingDate" },
      { label: "TVL", value: "tvl" },
    ],
  },
  organizations: {
    hasProjects: [
      { label: "Has projects", value: true },
      { label: "Has no projects", value: false },
    ],
    hasJobs: [
      { label: "Has jobs", value: true },
      { label: "Has no jobs", value: false },
    ],
    order: [
      { label: "Ascending", value: "asc" },
      { label: "Descending", value: "desc" },
    ],
    orderBy: [
      { label: "Head Count", value: "headcountEstimate" },
      { label: "Most Recent Funding Date", value: "recentFundingDate" },
      { label: "Rating", value: "rating" },
      { label: "Name", value: "name" },
    ],
  },
};

export const FILTER_CONFIG_PRESETS = {
  projects: {
    tvl: {
      position: 1,
      label: "TVL",
      show: true,
      googleAnalyticsEventName: "filter_search_tvl",
      kind: FilterKind.RANGE,
      prefix: "$",
    },
    monthlyVolume: {
      position: 2,
      label: "Volume/mo",
      show: false,
      googleAnalyticsEventName: "filter_search_monthly_volume",
      kind: FilterKind.RANGE,
      prefix: "$",
    },
    monthlyFees: {
      position: 3,
      label: "Fees/mo",
      show: false,
      googleAnalyticsEventName: "filter_search_monthly_fees",
      kind: FilterKind.RANGE,
      prefix: "$",
    },
    monthlyRevenue: {
      position: 4,
      label: "Revenue/mo",
      show: false,
      googleAnalyticsEventName: "filter_search_monthly_revenue",
      kind: FilterKind.RANGE,
      prefix: "$",
    },
    audits: {
      position: 5,
      label: "Audits",
      show: true,
      googleAnalyticsEventName: "filter_search_audits",
      kind: FilterKind.SINGLE_SELECT,
      options: SINGLE_SELECT_OPTIONS.projects.audits,
    },
    hacks: {
      position: 6,
      label: "Hacks",
      show: true,
      googleAnalyticsEventName: "filter_search_hacks",
      kind: FilterKind.SINGLE_SELECT,
      options: SINGLE_SELECT_OPTIONS.projects.hacks,
    },
    communities: {
      position: 7,
      label: "Communities",
      show: false,
      googleAnalyticsEventName: "filter_joblist_communities",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
    },
    mainNet: {
      position: 8,
      label: "Mainnet",
      show: true,
      googleAnalyticsEventName: "filter_search_is_mainnet",
      kind: FilterKind.SINGLE_SELECT,
      options: SINGLE_SELECT_OPTIONS.projects.mainNet,
    },
    token: {
      position: 9,
      label: "Has Token",
      show: true,
      googleAnalyticsEventName: "filter_search_has_token",
      kind: FilterKind.SINGLE_SELECT,
      options: SINGLE_SELECT_OPTIONS.projects.token,
    },
    order: {
      position: 10,
      label: "Order",
      show: true,
      googleAnalyticsEventName: "filter_search_order",
      kind: FilterKind.ORDER,
      options: SINGLE_SELECT_OPTIONS.projects.order,
    },
    orderBy: {
      position: 11,
      label: "Order By",
      show: true,
      googleAnalyticsEventName: "filter_search_order_by",
      kind: FilterKind.ORDER_BY,
      options: SINGLE_SELECT_OPTIONS.projects.orderBy,
    },
  },
  organizations: {
    headcountEstimate: {
      position: 1,
      label: "Head Count",
      show: true,
      googleAnalyticsEventName: "filter_search_head_count",
      kind: FilterKind.RANGE,
      prefix: null,
    },
    communities: {
      position: 2,
      label: "Communities",
      show: true,
      googleAnalyticsEventName: "filter_joblist_communities",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
    },
    ecosystems: {
      position: 3,
      label: "Ecosystems",
      show: true,
      googleAnalyticsEventName: "filter_search_ecosystems",
      kind: FilterKind.MULTI_SELECT_WITH_SEARCH,
    },
    hasJobs: {
      position: 4,
      label: "Has Jobs",
      show: true,
      googleAnalyticsEventName: "filter_search_has_jobs",
      kind: FilterKind.SINGLE_SELECT,
      options: SINGLE_SELECT_OPTIONS.organizations.hasJobs,
    },
    hasProjects: {
      position: 5,
      label: "Has Projects",
      show: true,
      googleAnalyticsEventName: "filter_search_has_projects",
      kind: FilterKind.SINGLE_SELECT,
      options: SINGLE_SELECT_OPTIONS.organizations.hasProjects,
    },
    order: {
      position: 6,
      label: "Order",
      show: true,
      googleAnalyticsEventName: "filter_search_order",
      kind: FilterKind.ORDER,
      options: SINGLE_SELECT_OPTIONS.organizations.order,
    },
    orderBy: {
      position: 7,
      label: "Order By",
      show: true,
      googleAnalyticsEventName: "filter_search_order_by",
      kind: FilterKind.ORDER_BY,
      options: SINGLE_SELECT_OPTIONS.organizations.orderBy,
    },
  },
  grants: {
    matchAmount: {
      position: 1,
      label: "Head Count",
      show: true,
      googleAnalyticsEventName: "filter_search_match_amount",
      kind: FilterKind.RANGE,
      prefix: "$",
    },
    donatedAmount: {
      position: 2,
      label: "Donated Amount",
      show: true,
      googleAnalyticsEventName: "filter_search_donated_amount",
      kind: FilterKind.RANGE,
      prefix: "$",
    },
    payoutTime: {
      position: 3,
      label: "Payout Time",
      show: true,
      googleAnalyticsEventName: "filter_search_payout_time",
      kind: FilterKind.RANGE,
      prefix: null,
    },
  },
  impact: {
    matchAmount: {
      position: 1,
      label: "Head Count",
      show: true,
      googleAnalyticsEventName: "filter_search_match_amount",
      kind: FilterKind.RANGE,
      prefix: "$",
    },
    donatedAmount: {
      position: 2,
      label: "Donated Amount",
      show: true,
      googleAnalyticsEventName: "filter_search_donated_amount",
      kind: FilterKind.RANGE,
      prefix: "$",
    },
    payoutTime: {
      position: 3,
      label: "Payout Time",
      show: true,
      googleAnalyticsEventName: "filter_search_payout_time",
      kind: FilterKind.RANGE,
      prefix: null,
    },
  },
};
