import * as Joi from "joi";

const envSchema = Joi.object({
  ALLOWED_ORIGINS: Joi.string(),
  APP_PORT: Joi.number().default(8080),
  AUTH0_AUDIENCE: Joi.string().required(),
  AUTH0_DOMAIN: Joi.string().required(),
  USER_CACHE_EXPIRATION_IN_DAYS: Joi.number().required(),
  DIFF: Joi.string(),
  EMAIL: Joi.string().required(),
  ETL_CLIENT_ID: Joi.string().required(),
  ETL_CLIENT_SECRET: Joi.string().required(),
  ETL_DOMAIN: Joi.string().required(),
  FE_DOMAIN: Joi.string().required(),
  GOOGLE_SERVICE_ACCOUNT_EMAIL: Joi.string().required(),
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: Joi.string().required(),
  INFURA_API_KEY: Joi.string().required(),
  JOB_PROMOTION_PRICE: Joi.number().required(),
  JWT_EXPIRES_IN: Joi.string().alphanum().required(),
  JWT_SECRET: Joi.string().alphanum().required(),
  LLAMA_PAY_API_KEY: Joi.string().required(),
  LLAMA_PAY_WEBHOOK_KEY: Joi.string().required(),
  MAGIC_LINK_EXPIRES_IN: Joi.string().required(),
  MAGIC_LINK_SECRET: Joi.string().required(),
  MW_DOMAIN: Joi.string().required(),
  NEO4J_HOST: Joi.string().required(),
  NEO4J_PASSWORD: Joi.string().required(),
  NEO4J_PORT: Joi.number().required(),
  NEO4J_SCHEME: Joi.string()
    .valid("bolt", "bolt+s", "bolt+scc", "neo4j", "neo4j+s", "neo4j+scc")
    .required(),
  NEO4J_USERNAME: Joi.string().required(),
  NEO4J_DATABASE: Joi.string().required(),
  NEO4J_HOST_TEST: Joi.string(),
  NEO4J_PASSWORD_TEST: Joi.string(),
  NEO4J_PORT_TEST: Joi.number(),
  NEO4J_SCHEME_TEST: Joi.string().valid(
    "bolt",
    "bolt+s",
    "bolt+scc",
    "neo4j",
    "neo4j+s",
    "neo4j+scc",
  ),
  NEO4J_USERNAME_TEST: Joi.string(),
  NEO4J_DATABASE_TEST: Joi.string(),
  NFT_STORAGE_API_KEY: Joi.string().required(),
  NODE_ENV: Joi.string()
    .valid("development", "production", "test", "staging")
    .default("development"),
  OPENAI_API_KEY: Joi.string().required(),
  ORG_ADMIN_DOMAIN: Joi.string().required(),
  PRIVY_APP_ID: Joi.string().required(),
  PRIVY_APP_SECRET: Joi.string().required(),
  PRIVY_WEBHOOK_KEY: Joi.string().required(),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().required(),
  REPORT_CONTENT_TO_EMAIL: Joi.string().required(),
  SCORER_API_KEY: Joi.string().required(),
  SCORER_DOMAIN: Joi.string().required(),
  SENDGRID_API_KEY: Joi.string().required(),
  SESSION_SECRET: Joi.string().required(),
  SENTRY_DSN: Joi.string().required(),
  SENTRY_TRACES_SAMPLE_RATE: Joi.number().required(),
  SKILL_THRESHOLD: Joi.number().required(),
  SWAGGER_USER: Joi.string().required(),
  SWAGGER_PASSWORD: Joi.string().required(),
  TEST_DB_MANAGER_URL: Joi.string(),
  TEST_DB_MANAGER_API_KEY: Joi.string(),
  VCDATA_API_KEY: Joi.string().required(),
});

export default envSchema;
