name: Continous Deployment
on:
  push:
    branches: [main, staging, dev]
jobs:
  release:
    name: Update Semver and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        id: semver
        with:
          semantic_version: 19
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/npm
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            semantic-release-slack-bot
      # - name: Sentry Release
      #   if: steps.semver.outputs.new_release_published == 'true'
      #   uses: getsentry/action-release@v1.4.1
      #   env:
      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #     SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      #   with:
      #     environment: ${{ github.ref_name }}
      #     version: ${{ steps.semver.outputs.new_release_version }}
      #     ignore_empty: true
      #     ignore_missing: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      # SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SEMANTIC_RELEASE_PACKAGE: "middleware"
