name: Continous Integration

################################
# Start the job on some events #
################################
on:
  push:
    branches: [dev, "feature/job-**", "fix/job-**"]
    paths:
      - "src/**.js"
      - "src/**.ts"
  pull_request:
    branches: [main, staging, dev]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Validate Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18.13.0
          cache: "yarn"
      ##################################################
      # Build the code base to check for syntax errors #
      ##################################################
      - name: Install Dependencies
        run: yarn install
      - name: Build Code
        run: yarn build
      - name: Cleanup
        run: rm -rf dist
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        run: yarn lint
      ##################
      # Run prod tests #
      ##################
      - name: Run Prod Tests
        run: yarn test --detectOpenHandles --forceExit
        env:
          NEO4J_HOST_TEST: ${{ secrets.NEO4J_HOST_TEST }}
          NEO4J_PASSWORD_TEST: ${{ secrets.NEO4J_PASSWORD_TEST }}
          NEO4J_PORT_TEST: ${{ secrets.NEO4J_PORT_TEST }}
          NEO4J_SCHEME_TEST: ${{ secrets.NEO4J_SCHEME_TEST }}
          NEO4J_USERNAME_TEST: ${{ secrets.NEO4J_USERNAME_TEST }}
          NEO4J_DATABASE_TEST: ${{ secrets.NEO4J_DATABASE_TEST }}
          TEST_DB_MANAGER_URL: ${{ secrets.TEST_DB_MANAGER_URL }}
          TEST_DB_MANAGER_API_KEY: ${{ secrets.TEST_DB_MANAGER_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SKILL_THRESHOLD: ${{ secrets.SKILL_THRESHOLD }}
          SCORER_API_KEY: ${{ secrets.SCORER_API_KEY }}
          SCORER_DOMAIN: ${{ secrets.SCORER_DOMAIN }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          APP_PORT: ${{ secrets.APP_PORT }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          LOCAL_HTTPS: ${{ secrets.LOCAL_HTTPS }}
          MAGIC_LINK_EXPIRES_IN: ${{ secrets.MAGIC_LINK_EXPIRES_IN }}
          MAGIC_LINK_SECRET: ${{ secrets.MAGIC_LINK_SECRET }}
          MW_DOMAIN: ${{ secrets.MW_DOMAIN }}
          FE_DOMAIN: ${{ secrets.FE_DOMAIN }}
          NFT_STORAGE_API_KEY: ${{ secrets.NFT_STORAGE_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          REPORT_CONTENT_TO_EMAIL: ${{ secrets.REPORT_CONTENT_TO_EMAIL }}
          SWAGGER_USER: ${{ secrets.SWAGGER_USER }}
          SWAGGER_PASSWORD: ${{ secrets.SWAGGER_PASSWORD }}
          VCDATA_API_KEY: ${{ secrets.VCDATA_API_KEY }}
          PRIVY_APP_ID: ${{ secrets.PRIVY_APP_ID }}
          PRIVY_APP_SECRET: ${{ secrets.PRIVY_APP_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLAMA_PAY_API_KEY: ${{ secrets.LLAMA_PAY_API_KEY }}
          LLAMA_PAY_WEBHOOK_KEY: ${{ secrets.LLAMA_PAY_WEBHOOK_KEY }}
          JOB_PROMOTION_PRICE: ${{ secrets.JOB_PROMOTION_PRICE }}
          ETL_CLIENT_ID: ${{ secrets.ETL_CLIENT_ID }}
          ETL_CLIENT_SECRET: ${{ secrets.ETL_CLIENT_SECRET }}
          ETL_DOMAIN: ${{ secrets.ETL_DOMAIN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
