name: Continous Integration

################################
# Start the job on some events #
################################
on:
  push:
    branches: [dev, "feature/job-**", "fix/job-**"]
    paths:
      - "src/**.js"
      - "src/**.ts"
  pull_request:
    branches: [main, staging, dev]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Validate Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: "yarn"
      ##################################################
      # Build the code base to check for syntax errors #
      ##################################################
      - name: Install Dependencies
        run: yarn install
      - name: Build Code
        run: yarn build
      - name: Cleanup
        run: rm -rf dist
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        run: yarn lint
      #####################
      # Run staging tests #
      #####################
      - name: Run Staging Tests
        run: yarn test --detectOpenHandles --forceExit
        env:
          NEO4J_HOST_TEST: ${{ secrets.NEO4J_HOST_TEST }}
          NEO4J_PASSWORD_TEST: ${{ secrets.NEO4J_PASSWORD_TEST }}
          NEO4J_PORT_TEST: ${{ secrets.NEO4J_PORT_TEST }}
          NEO4J_SCHEME_TEST: ${{ secrets.NEO4J_SCHEME_TEST }}
          NEO4J_USERNAME_TEST: ${{ secrets.NEO4J_USERNAME_TEST }}
          NEO4J_DATABASE_TEST: ${{ secrets.NEO4J_DATABASE_TEST }}
          TEST_DB_MANAGER_URL: ${{ secrets.TEST_DB_MANAGER_URL }}
          TEST_DB_MANAGER_API_KEY: ${{ secrets.TEST_DB_MANAGER_API_KEY }}
      ##################
      # Run prod tests #
      ##################
      - name: Run Prod Tests
        run: yarn test --detectOpenHandles --forceExit
        env:
          NEO4J_HOST_TEST: ${{ secrets.NEO4J_HOST_TEST }}
          NEO4J_PASSWORD_TEST: ${{ secrets.NEO4J_PASSWORD_TEST }}
          NEO4J_PORT_TEST: ${{ secrets.NEO4J_PORT_TEST }}
          NEO4J_SCHEME_TEST: ${{ secrets.NEO4J_SCHEME_TEST }}
          NEO4J_USERNAME_TEST: ${{ secrets.NEO4J_USERNAME_TEST }}
          NEO4J_DATABASE_TEST: ${{ secrets.NEO4J_DATABASE_TEST }}
          TEST_DB_MANAGER_URL: ${{ secrets.TEST_DB_MANAGER_URL }}
          TEST_DB_MANAGER_API_KEY: ${{ secrets.TEST_DB_MANAGER_API_KEY }}
