name: Continous Integration

################################
# Start the job on some events #
################################
on:
  push:
    branches: [dev, "feature/rip-**", "fix/rip-**"]
    paths:
      - "src/**.js"
      - "src/**.ts"
  pull_request:
    branches: [prod, main, dev]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Validate Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: "yarn"
      ##################################################
      # Build the code base to check for syntax errors #
      ##################################################
      - name: Install Dependencies
        run: yarn install
      - name: Build Code
        run: yarn build
      - name: Cleanup
        run: rm -rf dist
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        run: yarn lint
      ##################
      # Run prod tests #
      ##################
      - name: Run Prod Tests
        run: yarn test --detectOpenHandles
        env:
          NEO4J_HOST: ${{ secrets.NEO4J_HOST_PROD }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD_PROD }}
          NEO4J_PORT: ${{ secrets.NEO4J_PORT_PROD }}
          NEO4J_SCHEME: ${{ secrets.NEO4J_SCHEME_PROD }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME_PROD }}
      #####################
      # Run staging tests #
      #####################
      - name: Run Staging Tests
        run: yarn test --detectOpenHandles
        env:
          NEO4J_HOST: ${{ secrets.NEO4J_HOST_STAGING }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD_STAGING }}
          NEO4J_PORT: ${{ secrets.NEO4J_PORT_STAGING }}
          NEO4J_SCHEME: ${{ secrets.NEO4J_SCHEME_STAGING }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME_STAGING }}
