name: Fly Deploy
on:
  push:
    branches: [prod, main, dev]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Dev Deployment
        if: github.ref_name == 'dev'
        run: flyctl deploy --remote-only --region sin --app middleware-dev --env NODE_ENV=development --env SENTRY_TRACES_SAMPLE_RATE=1.0 --env SENTRY_DSN=$SENTRY_DSN
      - name: Staging Deployment
        if: github.ref_name == 'main'
        run: flyctl deploy --remote-only --region sin --app middleware-staging --env NODE_ENV=staging --env SENTRY_DSN=$SENTRY_DSN
      - name: Prod Deployment
        if: github.ref_name == 'prod'
        run: flyctl deploy --remote-only --region sin --app middleware-prod --env NODE_ENV=production --env SENTRY_DSN=$SENTRY_DSN
