name: Sentry Release
on:
  push:
    branches: [prod, main, dev]
jobs:
  sentry-release:
    name: Publish release to Sentry
    runs-on: ubuntu-latest
    steps:
      - uses: rickstaa/action-get-semver@v1
        id: get_semver
        with:
          verbose: true
      - name: Sentry Release
        uses: getsentry/action-release@v1.2.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ github.ref_name }}
          sourcemaps: "./dist"
          version: ${{ steps.get_semver.outputs.current_version  }}
